In [22]:
import cv2
import glob

In [15]:
img = cv2.imread("galaxy.jpg",1)

In [16]:
print(type(img))

<class 'numpy.ndarray'>


In [17]:
print(img)

[[[19 15 10]
  [23 19 14]
  [21 15  8]
  ...
  [27 22 13]
  [22 17  8]
  [23 18  9]]

 [[17 13  8]
  [21 17 12]
  [19 13  6]
  ...
  [27 22 13]
  [22 17  8]
  [24 19 10]]

 [[17 14  6]
  [18 15  7]
  [21 18 10]
  ...
  [23 16  7]
  [33 26 17]
  [30 23 14]]

 ...

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 5  5  5]
  [ 8  8  8]
  [14 14 14]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 2  2  2]
  [ 3  3  3]
  [ 9  9  9]]

 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 3  3  3]]]


In [18]:
res_img = cv2.resize(img,(1000,500))
cv2.imshow("Galaxy",res_img)
cv2.imwrite("Galaxyrs.jpg",res_img)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [33]:
images=glob.glob("*.jpg")

In [35]:
for image in images:
    img=cv2.imread(image,1)
    re=cv2.resize(img,(100,100))
    cv2.imshow("Hey",re)
    cv2.waitKey(1000)
    cv2.destroyAllWindows()
    cv2.imwrite("resized_"+ image, re)